### ISSUE TITLE
Windows-style paths result in module name / path mismatch

### ISSUE THREAD

**Issue by typeswitch-dev** [mirth-lang/mirth#199]
Passing windows-style path for the input file results in an error that the module name doesn't match the path, e.g.:

```
M:\> bin\mirth0.exe -o mirth.c mirth\main.mth
Compiling mirth\main.mth
Building.
src/mirth\main.mth:1:8: error: expected module name to match path
mirth/main.mth
mirth\main.mth
```

[The tricky bit is figuring out how to fix this without breaking the golden tests on windows. Maybe we need to add a command-line option to use unix paths regardless of the operating system, and use that in the test script.]

**Comment by kephas** [comment]
Is there a drawback to converting Windows-style paths to unix paths before using them?

**Comment by typeswitch-dev** [comment]
Oh this has already been fixed.
