### ISSUE TITLE
Floating Point

### ISSUE THREAD

**Issue by Capital-EX** [mirth-lang/mirth#313]
Mirth currently lacks floating point which makes some task extremely impracticable. It also can't bind floats over the existing C FFI. It'd be nice to have `F32` and `F64` along side `CFloat` and `CDouble`.

**Comment by casuallyblue** [comment]
as of PR #314 there is now 64 bit floating point support. F32 and its associated C FFI bindings are in progress.

**Comment by typeswitch-dev** [comment]
`F32` and `F64` are both supported now.

There isn't a C-specific version of `F32` and `F64`, because `float` and `double` in C are always 32 and 64 bits respectively, so we can just use `F32` and `F64` in the bindings (like how we can use fixed-size integers `U8`, `U16`, etc the same way).
