### ISSUE TITLE
snake isn't built

### ISSUE THREAD

**Issue by kephas** [mirth-lang/mirth#67]
I tried building `snake` but `snake.c` isn't generated:
```
$ make bin/snake
bin/mirth2
Building.
Done.
rm -f bin/mirth.c
gcc -std=c99 -Wall -Wextra -Wno-unused-function -Wno-unused-parameter -Werror -pedantic -o bin/snake bin/snake.c `pkg-config --libs sdl2`
gcc: error: bin/snake.c: No such file or directory
make: *** [Makefile:74: bin/snake] Error 1
```

**Comment by sofiafaro** [comment]
Hi @kephas!

To get snake building, you will need to uncomment the line containing `import(snake)` in `src/main.mth` (line 67). I.e., turn it into

```
import(snake)
```

Then `make bin/snake` and `make play-snake` should work, assuming sdl2 is installed. Please let me know if you run into an issue.

(This is terrible UI, I know. I'm sorry, and I will fix it.)

**Comment by kephas** [comment]
Changed `mirth.mth` and it works like a charm!
